---
abstract: 'Arrays as objects with lots of handy methods'
author:
  - 'Ron Savage <ron@savage.net.au>'
build_requires:
  Test::Deep: 0
  Test::More: 0
  Test::Pod: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.4, CPAN::Meta::Converter version 2.113640'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Set-Array
provides:
  Set::Array:
    file: lib/Set/Array.pm
    version: 0.24
requires:
  Carp: 0
  Want: 0
resources:
  license: http://opensource.org/licenses/artistic-license.php
version: 0.24
