---
abstract: 'Arrays as objects with lots of handy methods'
author:
  - 'Ron Savage <ron@savage.net.au>'
build_requires:
  Test::Deep: 0.108
  Test::More: 0.47
  Test::Pod: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120630'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Set-Array
provides:
  Set::Array:
    file: lib/Set/Array.pm
    version: 0.27
requires:
  Carp: 0
  Try::Tiny: 0.11
  Want: 0
  attributes: 0.06
  overload: 1.01
  strict: 1.03
  subs: 1
  warnings: 1.03
resources:
  license: http://www.perlfoundation.org/artistic_license_1_0
version: 0.27
